### ISSUE TITLE
Images in Orte 

### ISSUE THREAD

**Issue by Jarami110d** [a-thousand-channels/ORTE-backend#188]
1- When a picture is uploaded to an entry, it would be good to be able to select the part of the image that is show in the Preview pop up Window.

-- currently by Portrait format imagines the top corner is shown as preview
--Update wish: the possibility to select manually the are of the picture that should be displayed as preview or at least the auto selection of the middle area of the image.

example: Queer.topia 2021 layer / June 

2- The quality of images is drastically dropped in the full image view. 

example: https://orte.link/maps/9/layers/70/places/850

**Comment by ut** [comment]
fixed, i think :)

**Comment by ut** [comment]
to be more verbose. 
* the image quality is now increased up 1200 pixels width/height
* the preview image in portait mode (in the popups on the map) are not cropped anymore in desktop mode, in smaller screen the cropping has been decreased

"--Update wish: the possibility to select manually the are of the picture that should be displayed as preview or at least the auto selection of the middle area of the image."

this feature might be not necessary anymore, since the image should be displayed in full now :)))  what do you think?
